### ISSUE TITLE
Where to download?

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/redeclipse-appimage#1]
Where can the AppImage be downloaded?

**Comment by TheAssassin** [comment]
As implied [here](https://github.com/red-eclipse/base/issues/175#issuecomment-279162064), there's no AppImage releases yet. We are discussing this internally at the moment. If we should decide to not officially distribute AppImages, I will upload them as third party builds in the releases section of this repository.

**Comment by TheAssassin** [comment]
After discussing this internally, we decided to upload AppImages to https://github.com/red-eclipse/base.
