### ISSUE TITLE
Use type 2 AppImages

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/redeclipse-appimage#2]
By using `generate_type2_appimage` instead of `generate_appimage`, you get a more modern squashfs-based type 2 AppImage. It should be a bit smaller, faster, and allow for embedding gpg2 digital signatures.

**Comment by TheAssassin** [comment]
Oops. Actually I wanted to comment that I will try this, and compare the results.

**Comment by TheAssassin** [comment]
```
$ du -sh out/*
862M	out/Red_Eclipse-1.5.6-x86_64.AppImage
900M	out/redeclipse-1.5.6-x86_64.AppImage
```

Well, as expected, the size difference is quite small. Compression of already compressed media data is almost impossible. But anyway, I like the new features of the type 2 images (you can permanently mute the "do you want to install me" messages for example). I am going to implement this in the next commit.

About the digital signatures: If I should happen to be interested in that feature, I will create a separate issue.
